

menus:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  # Changelog: /changelog
  # ......



favicon: /images/favicon.svg





footer:
  since: 2020
  icp: 京ICP备00000001号
  


version: 1.0.0



